#Application Configuration // En que puerto se va a ejecutar
#Hola
server:
  port: 9003

#To See H2 Console in Browser:
#http://localhost:8091/h2-console // Habilitando el H2 Console para poder ver los datos enbebidos H2.
#Enabling H2 Console
spring:
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

# ==================================
# DB
# ==================================
datasource:
  url: jdbc:h2:mem:SALESYSTEM
  driverClassName: org.h2.Driver
  platform: h2
  username: noodle
  password:

# ==================================
# JPA / HIBERNATE
# ==================================
jpa:
  show-sql: true # Que muestre los SQL que vamos a insert, update en la BD y que lo muestre en el log
  hibernate:
    ddl-auto: create-drop # Hace un update en el esquema de BD de acuerdo al mapper de nuestras clases
  database-platform: org.hibernate.dialect.H2Dialect
  properties:
    hibernate:
      show-sql: true
      use-sql-comments: false
      format-sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

#spring.config.import=configserver:http://localhost:8888
